### ISSUE TITLE
The repaired contracts and tx replay tests

### ISSUE THREAD

**Issue by mojtaba-eshghie** [Anonymous123xx/RLRep#1]
Hi, 

I am a Ph.D. student at KTH Royal Insitute of Technology interested in your work. Is it possible to have the repaired version of the contracts? Furthermore, I would also be thankful to have the replay tests as well. I could not find these two in the [dataset_vul.tar.gz](https://github.com/Anonymous123xx/RLRep/blob/main/dataset_vul.tar.gz) file. I wish not to run the experiments myself since probably you have done it with optimum configs. 

Thank you!

**Comment by Anonymous123xx** [comment]
We have updated the contracts data that can be fixed correctly. We have also uploaded the addresses of the contracts in the validation set on Ethereum which are in the file `address.csv`. If you need information related to the test cases used for replay, you can download the corresponding transactions on [Etherscan](https://etherscan.io/) via the contract addresses.
