### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by SpicyTurkey** [Anonymous123xx/RLRep#3]
Hi,
As a graduate student, I am eager to learn about your repair idea and was planning to try it out. However, I have encountered some issues: You mentioned 'Enter the antlr4 package and find the RuleContext.py and Trees.py', but these .py files are not available on GitHub. Do I need to create them myself?
Thank you!

**Comment by Henrykwokkk** [comment]
Use Pycharm and click 'tree' class. Then you can enter the corresponding py file and modify and add the function.

**Comment by Anonymous123xx** [comment]
Use Pycharm and click 'tree' class in line 37 of utils2.py. Then you can enter the corresponding py file and modify and add the function.

**Comment by SpicyTurkey** [comment]
> Use Pycharm and click 'tree' class in line 37 of utils2.py. Then you can enter the corresponding py file and modify and add the function.

Oh, thank you so much! 
I attempted to open the home directory in vscode and discovered the SolidityParser class for tree in utils2.py. When I tried to jump to SolidityParser and found def sempred(self, localctx:RuleContext, ruleIndex:int, predIndex:int), which includes RuleContext. However, when I clicked on RuleContext to jump, it only took me to a pyi file. Is this correct?
Or I need to add the toCodeSequence() declaration to SolidityParser.py
Thank you again!

**Comment by Anonymous123xx** [comment]
I think the former is correct. You don't need to modify SolidityParser.py. I have not used vscode. You can try to use it to implement the process.

**Comment by SpicyTurkey** [comment]
> I think the former is correct. You don't need to modify SolidityParser.py. I have not used vscode. You can try to use it to implement the process.

Thank you so much for your patience!
If possible, I would appreciate confirming it once again. It can be found in the "RLRep\ SolidityParser \ solidityParser.py" file under the class SolidityParser (Parser). Please add the "def toCodeSequence(...)" function. Are these correct?

**Comment by Anonymous123xx** [comment]
You don't need to modify SolidityParser.py. Just add 'toCodeSequence(self, ruleNames:list=None, recog:Parser=None)' in RuleContext.py and 'toCodeSequence(cls, t:Tree, ruleNames:list=None, recog:Parser=None)' in Tree.py respectively. Clicking 'Trees' class in RuleContext.py can jump to Tree.py

**Comment by SpicyTurkey** [comment]
> You don't need to modify SolidityParser.py. Just add 'toCodeSequence(self, ruleNames:list=None, recog:Parser=None)' in RuleContext.py and 'toCodeSequence(cls, t:Tree, ruleNames:list=None, recog:Parser=None)' in Tree.py respectively. Clicking 'Trees' class in RuleContext.py can jump to Tree.py

Thank you so much! 
It was incredibly enlightening. However, I couldn't find RuleContext.py in my RLRep directory, only RuleConntext.pyi. This issue is really frustrating me. TAT
I have to kindly ask you to answer again. Thank you for your patience and understanding!

**Comment by Anonymous123xx** [comment]
It may refer to the use of vscode. Try to check the configuration of vscode or use Pycharm.

**Comment by SpicyTurkey** [comment]
Thank you so much！
I'll try!

**Comment by SpicyTurkey** [comment]
When looking for RuleContext.py and Trees.py, if you use a virtual environment, you'll need to look in the virtual environment's lib-python-site-packages.
